# Generated by Django 2.1.5 on 2019-02-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
