# Generated by Django 2.1.5 on 2019-02-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190202_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
