# Generated by Django 2.1.5 on 2019-02-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190202_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='donation',
            field=models.PositiveIntegerField(),
        ),
    ]
